packages:
  - "packages/*"
  - "apps/*"

allowBuilds:
  '@clerk/shared': true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  dtrace-provider: false
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - nativewind@4.2.6
  - react-native-css-interop@0.2.6

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
