-- Web push notifications: device subscriptions, nudge log

-- One row per browser push subscription. A subscription belongs to a signed-in
-- user (user_id), an anonymous participant on one receipt (participant_id), or
-- both once a guest signs in and their claim is replayed.
CREATE TABLE public.push_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint text NOT NULL UNIQUE,
    p256dh text NOT NULL,
    auth text NOT NULL,
    user_id text,
    participant_id bigint REFERENCES public.participants(id),
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT push_subscriptions_identity_check CHECK (user_id IS NOT NULL OR participant_id IS NOT NULL)
);

CREATE INDEX idx_push_subscriptions_user_id ON public.push_subscriptions (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX idx_push_subscriptions_participant_id ON public.push_subscriptions (participant_id) WHERE participant_id IS NOT NULL;

-- Nudge log: powers the per-(receipt, target) rate limit and keeps history.
CREATE TABLE public.nudges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id bigint NOT NULL REFERENCES public.receipts(id),
    participant_id bigint NOT NULL REFERENCES public.participants(id),
    sender_user_id text,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE INDEX idx_nudges_receipt_participant ON public.nudges (receipt_id, participant_id, created_at DESC);
